### ISSUE TITLE
增加集成失敗

### ISSUE THREAD

**Issue by kit294** [rxwen/homeassistant-terncy-component#22]
Failed to add integration
only Not all required fields are filled in showed

**Comment by kit294** [comment]
查找了log 有關的就只有
2023-02-03 16:24:02.915 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration terncy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by kit294** [comment]
我的是Raspberry pi 4 
Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by kit294** [comment]
已經跟上教學把檔案拉到custom_components
但安裝集成時彈出視窗按submit 就出現Not all required fields are filled in showed

**Comment by rxwen** [comment]
> 查找了log 有關的就只有 2023-02-03 16:24:02.915 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration terncy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

这个日志是正常的警告提示，不是直接的错误原因。应该没有关系的。

**Comment by rxwen** [comment]
> 已經跟上教學把檔案拉到custom_components 但安裝集成時彈出視窗按submit 就出現Not all required fields are filled in showed

有其他错误日志吗？

**Comment by rxwen** [comment]
https://github.com/rxwen/homeassistant-terncy-component/issues/20

参考这个issue下的修改网络参数方法试试看呢？

**Comment by kit294** [comment]
> > 已經跟上教學把檔案拉到custom_components 但安裝集成時彈出視窗按submit 就出現Not all required fields are filled in showed
> 
> 有其他错误日志吗？

就是沒有任何錯誤的日誌

**Comment by kit294** [comment]
> #20
> 
> 参考这个issue下的修改网络参数方法试试看呢？

我也有看過這個issue, 但是我是樹莓派4裝的ha 也要改的嗎，那裡可以改？

**Comment by kit294** [comment]
[](https://ibb.co/MnHmH2w) 
就只有這個訊息

**Comment by rxwen** [comment]
我没有树莓派，无法测试这个场景。

用docker验证了对2023.2.1的ha的支持是没有问题的。

**Comment by rxwen** [comment]
如果是在ha上直接跑，我的理解是它可以直接用到系统的网络，不需要做这个host网络配置。

**Comment by kit294** [comment]
[我就是卡在了06:06這一步](https://m.bilibili.com/video/BV1X54y187nq)

**Comment by kit294** [comment]
如果真的增加不了集成，可以教我如何在zigbee2mqtt手動增加畢方的雙色溫射燈嗎
[我就只有這個設備](https://ibb.co/sm6sxLN)

**Comment by kit294** [comment]
今天的log 是這樣的
2023-02-03 17:13:10.593 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration terncy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-03 17:13:10.596 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-02-03 17:13:36.864 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [548361996944] Disconnected: Did not receive auth message within 10 seconds
2023-02-03 18:00:35.021 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-03 18:00:37.051 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-03 18:01:57.957 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-03 18:02:00.020 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-03 18:03:48.697 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-03 18:03:53.538 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-04 02:45:56.817 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-04 02:45:59.442 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-04 10:12:52.365 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-04 10:12:55.536 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error.
2023-02-04 11:37:47.739 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.1.6 (192.168.1.6). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.2 (io.robbie.HomeAssistant; build:2023.444; iOS 15.7.0) Mobile/HomeAssistant, like Safari)
2023-02-04 11:47:45.032 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got 'custom_components.terncy:debug homeassistant.components.terncy:debug'. (See /config/configuration.yaml, line 17). 
2023-02-04 11:47:45.042 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547908205536] The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got 'custom_components.terncy:debug homeassistant.components.terncy:debug'. (See /config/configuration.yaml, line 17). 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 529, in async_handle_core_service
    raise HomeAssistantError(

**Comment by kit294** [comment]
2023-02-04 23:30:27.121 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'manifest/get', 'integration': 'terncy', 'id': 104}
2023-02-04 23:30:27.123 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Sending {"id":104,"type":"result","success":true,"result":{"domain":"terncy","name":"Terncy","version":"1.0.6","config_flow":true,"documentation":"https://www.home-assistant.io/integrations/terncy","requirements":["terncy==0.3.5","websockets==10.3","zeroconf>=0.28.8"],"zeroconf":[{"type":"_websocket._tcp.local.","name":"box-*"}],"dependencies":[],"after_dependencies":["discovery"],"codeowners":["@rxwen"],"is_built_in":false}}
2023-02-04 23:30:27.195 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'config', 'integration': ['terncy'], 'id': 105}
2023-02-04 23:30:27.199 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'selector', 'integration': ['terncy'], 'id': 106}
2023-02-04 23:30:27.200 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'title', 'integration': ['terncy'], 'id': 107}
2023-02-04 23:30:27.202 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Sending {"id":105,"type":"result","success":true,"result":{"resources":{"component.terncy.config.abort.already_configured":"This Home Center has already been configured.","component.terncy.config.error.invalid_auth":"Please approve access request in Terncy app first","component.terncy.config.error.need_new_auth":"Request a new token, then approve access request in Terncy app first, then submit again","component.terncy.config.flow_title":"Terncy: {name}","component.terncy.config.step.user.data.device":"Device","component.terncy.config.step.confirm.description":"You are about to add the `{name}` to Home Assistant.\n\n**To complete the process, you may have to approve access request in Terncy App after you submit access request.**\n\n","component.terncy.config.step.confirm.title":"Confirm adding Terncy Home Center","component.terncy.config.step.begin_pairing.description":"You are adding the `{name}` to Home Assistant.\n\n**To complete the process, please approve the access request in Terncy App. Then submit again.**\n\n","component.terncy.config.step.begin_pairing.title":"Adding Terncy Home Center"}}}
2023-02-04 23:30:27.205 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Sending [{"id":106,"type":"result","success":true,"result":{"resources":{}}},{"id":107,"type":"result","success":true,"result":{"resources":{"component.terncy.title":"Terncy"}}}]
朋友教我開了debug log
這個會是有關的嗎

**Comment by rxwen** [comment]
> 今天的log 是這樣的 2023-02-03 17:13:10.593 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration terncy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant 2023-02-03 17:13:10.596 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant 2023-02-03 17:13:36.864 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [548361996944] Disconnected: Did not receive auth message within 10 seconds 2023-02-03 18:00:35.021 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-03 18:00:37.051 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-03 18:01:57.957 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-03 18:02:00.020 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-03 18:03:48.697 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-03 18:03:53.538 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-04 02:45:56.817 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-04 02:45:59.442 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-04 10:12:52.365 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-04 10:12:55.536 ERROR (MainThread) [frontend.js.latest.202302020] :0:0 Script error. 2023-02-04 11:37:47.739 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.1.6 (192.168.1.6). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.2 (io.robbie.HomeAssistant; build:2023.444; iOS 15.7.0) Mobile/HomeAssistant, like Safari) 2023-02-04 11:47:45.032 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got 'custom_components.terncy:debug homeassistant.components.terncy:debug'. (See /config/configuration.yaml, line 17). 2023-02-04 11:47:45.042 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547908205536] The system cannot restart because the configuration is not valid: Invalid config for [logger]: expected a dictionary for dictionary value @ data['logger']['logs']. Got 'custom_components.terncy:debug homeassistant.components.terncy:debug'. (See /config/configuration.yaml, line 17). Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service await hass.services.async_call( File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call task.result() File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)( File "/usr/src/homeassistant/homeassistant/components/hassio/**init**.py", line 529, in async_handle_core_service raise HomeAssistantError(

这个日志不全，最后的错误是什么正好截断了

**Comment by rxwen** [comment]
> 2023-02-04 23:30:27.121 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'manifest/get', 'integration': 'terncy', 'id': 104} 2023-02-04 23:30:27.123 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Sending {"id":104,"type":"result","success":true,"result":{"domain":"terncy","name":"Terncy","version":"1.0.6","config_flow":true,"documentation":"[https://www.home-assistant.io/integrations/terncy","requirements":["terncy==0.3.5","websockets==10.3","zeroconf>=0.28.8"],"zeroconf":[{"type":"_websocket._tcp.local.","name":"box-*"}],"dependencies":[],"after_dependencies":["discovery"],"codeowners":["@rxwen"],"is_built_in":false}}](https://www.home-assistant.io/integrations/terncy%22,%22requirements%22:%5B%22terncy==0.3.5%22,%22websockets==10.3%22,%22zeroconf%3E=0.28.8%22%5D,%22zeroconf%22:%5B%7B%22type%22:%22_websocket._tcp.local.%22,%22name%22:%22box-*%22%7D%5D,%22dependencies%22:%5B%5D,%22after_dependencies%22:%5B%22discovery%22%5D,%22codeowners%22:%5B%22@rxwen%22%5D,%22is_built_in%22:false%7D%7D) 2023-02-04 23:30:27.195 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'config', 'integration': ['terncy'], 'id': 105} 2023-02-04 23:30:27.199 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'selector', 'integration': ['terncy'], 'id': 106} 2023-02-04 23:30:27.200 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'title', 'integration': ['terncy'], 'id': 107} 2023-02-04 23:30:27.202 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Sending {"id":105,"type":"result","success":true,"result":{"resources":{"component.terncy.config.abort.already_configured":"This Home Center has already been configured.","component.terncy.config.error.invalid_auth":"Please approve access request in Terncy app first","component.terncy.config.error.need_new_auth":"Request a new token, then approve access request in Terncy app first, then submit again","component.terncy.config.flow_title":"Terncy: {name}","component.terncy.config.step.user.data.device":"Device","component.terncy.config.step.confirm.description":"You are about to add the `{name}` to Home Assistant.\n\n**To complete the process, you may have to approve access request in Terncy App after you submit access request.**\n\n","component.terncy.config.step.confirm.title":"Confirm adding Terncy Home Center","component.terncy.config.step.begin_pairing.description":"You are adding the `{name}` to Home Assistant.\n\n**To complete the process, please approve the access request in Terncy App. Then submit again.**\n\n","component.terncy.config.step.begin_pairing.title":"Adding Terncy Home Center"}}} 2023-02-04 23:30:27.205 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547831846400] Sending [{"id":106,"type":"result","success":true,"result":{"resources":{}}},{"id":107,"type":"result","success":true,"result":{"resources":{"component.terncy.title":"Terncy"}}}] 朋友教我開了debug log 這個會是有關的嗎

readme里说的授权操作做了吗？
