### ISSUE TITLE
关于小燕断电后在HA掉线 的问题

### ISSUE THREAD

**Issue by xzshow** [rxwen/homeassistant-terncy-component#23]
从用小燕到现在，一直是这样，重载集成或者断电后再上电，HA就掉了，400的网关和200多的网关都 这样，目前看到400多的网关的日志，200多好像没日志，400多的点重载弯黄，200多的点集成不会黄，但灯什么的控制 不了，这是昨天的测试版21的日志

2023-02-09 14:54:12.456 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 客厅百灵 for terncy
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
result = await component.async_unload_entry(hass, self)
File "/config/custom_components/terncy/__init__.py", line 517, in async_unload_entry
hass.data[DOMAIN].pop(entry.entry_id)
KeyError: '8e54eb72f1ff399eefa867139ad50198'

2023-02-09 14:50:53.993 ERROR (MainThread) [homeassistant.components.light] Platform terncy does not generate unique IDs. ID 0x0000000018175187-01 already exists - ignoring light.123
2023-02-09 14:50:54.008 ERROR (MainThread) [homeassistant.components.light] Platform terncy does not generate unique IDs. ID 2c1165fffeebbbc6-01 already exists - ignoring light.jiu_ju_deng
2023-02-09 14:50:54.201 ERROR (MainThread) [homeassistant.components.light] Platform terncy does not generate unique IDs. ID 540f57fffe4eeeea-01 already exists - ignoring light.can_deng_4

**Comment by xzshow** [comment]
而且之前加的设备，坏了，实体删除，但还没地方删除，也莫名出现我之前命名的灯现在改名了，之前的名称还在里面届没法删除

**Comment by xzshow** [comment]
![12345678901](https://user-images.githubusercontent.com/110080681/217743278-4ae5b343-54d6-444c-9c1a-4f07577ba4a4.png)

**Comment by xzshow** [comment]
400多网关的状态
![QQ截图20230209155732](https://user-images.githubusercontent.com/110080681/217755830-c55f6364-bb4d-4606-b637-864627439187.png)

**Comment by xzshow** [comment]
200多状态
![QQ截图20230209155939](https://user-images.githubusercontent.com/110080681/217755956-37b1a962-8635-4a56-bf35-b87fbb3f02d8.png)
实际上是不可控制的

**Comment by lifetimr** [comment]
我这边遇到和你同样的问题，只能通过重启HA或者重新安装插件的方式才能恢复正常，且需要尝试多次

**Comment by lifetimr** [comment]
我这边遇到和你同样的问题，只能通过重启HA或者重新安装插件的方式才能恢复正常，且需要尝试多次，重载之后可以看到设备的当前状态，但实体不可用

**Comment by ThanYi1** [comment]
我也出现能看状态不能读取的情况，不知道怎么处理
