### ISSUE TITLE
integration won't load

### ISSUE THREAD

**Issue by mygithandle** [rxwen/homeassistant-terncy-component#6]
extracted homeassistant-terncy-component-1.0.10  as instructed.

After re-start I have as below:
├── automations.yaml
├── blueprints
├── configuration.yaml
├── custom_components
       ├──__init__.py
       ├── __pycache__
       ├── binary_sensor.py
       ├── config_flow.py
       ├── const.py
       ├── cover.py
       ├── device_trigger.py
       ├── hub_monitor.py
       ├── light.py
       ├── manifest.json
       ├── sensor.py
       ├── strings.json
       ├── switch.py
       ├── translations
       ├──utils.py
├── deps
├── groups.yaml . . .
 . . . .

Log:
```
Logger: homeassistant.loader Source: custom_components/__init__.py:5  Integration: __init__.py  First occurred: 3:32:49 PM (1 occurrences)  Last logged: 3:32:49 PM
Error loading custom_components.panel_custom. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 639, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/__init__.py", line 5, in <module>
    import terncy
ModuleNotFoundError: No module named 'terncy'
```

This on:
```
HA Version | core-2021.12.10
Python Version | 3.9.7
Linux Version | 5.10.63-v8
```
How to fix ?

**Comment by mygithandle** [comment]
resolved. must extract to new folder "terncy" in custom_components 

successful structure is 



After re-start I have as below:
```
├── automations.yaml
├── blueprints
├── configuration.yaml
├── custom_components
    ├── terncy
        ├──__init__.py
        ├── binary_sensor.py
        ├── config_flow.py
        ├── const.py
        ├── cover.py
        ├── device_trigger.py
. . . .
etc...

integration then works.

@rxwen suggest you modify GitHub install instructions

**Comment by rxwen** [comment]
Thanks for reporting. Fixed in https://github.com/rxwen/homeassistant-terncy-component/commit/b8380b2c7c9356d149a04e07b36f442bc8937554.
