### ISSUE TITLE
正在设置 Terncy，请稍候

### ISSUE THREAD

**Issue by liuxiang91** [rxwen/homeassistant-terncy-component#9]
Home assistant docker 部署
小燕 1.0.14 版本
正在设置 Terncy，请稍候  会转很久

**Comment by liuxiang91** [comment]
之后出现 无法加载配置向导: 500 Internal Server Error Server got itself in trouble

**Comment by rxwen** [comment]
请问ha的版本是多少？
可以通过首页readme最底部提供的方式获取ha的日志看看。

**Comment by liuxiang91** [comment]
## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.100
arch | x86_64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4968
Installed Version | 1.22.0
Stage | running
Available Repositories | 1080
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 11
added_devices | 3

</details>

**Comment by liuxiang91** [comment]
Logger: aiohttp.server
Source: requirements.py:180 
First occurred: 12:23:26 (6 occurrences) 
Last logged: 16:21:12

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 132, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 730, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 351, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in _async_process_integration
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 162, in async_process_requirements
    await _async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 180, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for terncy not found: ['terncy==0.3.5'].

**Comment by rxwen** [comment]
看起来可能是这个ha实例的网络问题，它无法从公网下载到依赖的 terncy 0.3.5 版本插件。
这个插件本身只有一个版本，不太可能是由于版本冲突导致的。

**Comment by rxwen** [comment]
用更老版的terncy插件，1.0.9 是否曾经正常？

**Comment by liuxiang91** [comment]
解决了。是我的docker pip 访问外网有问题，估计是被墙了。在ha bash里手动执行 pip install terncy  -i https://pypi.tuna.tsinghua.edu.cn/simple 解决了。谢谢
